export const SWITCH_NETWORK = 'SWITCH_NETWORK'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const ADD_CUSTOM_NETWORK = 'ADD_CUSTOM_NETWORK'
export const DELETE_CUSTOM_NETWORK = 'DELETE_CUSTOM_NETWORK'
